language: csharp
solution: nacos-sdk-csharp.sln
os:
  - osx
  - linux

sudo: required
dist: bionic

osx_image: xcode9.4

mono: none

dotnet: 3.1.101


script:
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore --disable-parallel; fi
  - dotnet build -c Release